/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.ayolan.public_access.user.login;

import java.sql.ResultSet;
import com.softidea.www.public_access.DB.MC_JavaDataBaseConnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author THINK IT
 */
public final class user_login extends javax.swing.JFrame {

    /**
     * Creates new form user_login
     */
    public user_login() {
        initComponents();
        showDate();
        showTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_time_date = new javax.swing.JLabel();
        lb_date_view = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _pf_user_login_password = new javax.swing.JPasswordField();
        _tf_user_loging_userName = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        logo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        seperatorBar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lb_time_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_time_date.setForeground(new java.awt.Color(255, 255, 255));
        lb_time_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_time_date.setText("lb_time_date");

        lb_date_view.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_date_view.setForeground(new java.awt.Color(255, 255, 255));
        lb_date_view.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_date_view.setText("lb_date_view");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(1249, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_time_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_date_view, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lb_time_date)
                .addGap(4, 4, 4)
                .addComponent(lb_date_view)
                .addGap(5, 5, 5))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1370, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 260, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lb_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_exit.setForeground(new java.awt.Color(255, 0, 0));
        lb_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exit.setText("X");
        lb_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_exitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lb_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1334, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email Address:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 300, 20));

        _pf_user_login_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _pf_user_login_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _pf_user_login_password.setMaximumSize(new java.awt.Dimension(300, 40));
        _pf_user_login_password.setMinimumSize(new java.awt.Dimension(300, 40));
        _pf_user_login_password.setPreferredSize(new java.awt.Dimension(300, 40));
        _pf_user_login_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _pf_user_login_passwordActionPerformed(evt);
            }
        });
        _pf_user_login_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _pf_user_login_passwordKeyTyped(evt);
            }
        });
        getContentPane().add(_pf_user_login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 300, -1));

        _tf_user_loging_userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_user_loging_userName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _tf_user_loging_userName.setMaximumSize(new java.awt.Dimension(300, 40));
        _tf_user_loging_userName.setMinimumSize(new java.awt.Dimension(300, 40));
        _tf_user_loging_userName.setPreferredSize(new java.awt.Dimension(300, 40));
        _tf_user_loging_userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _tf_user_loging_userNameKeyTyped(evt);
            }
        });
        getContentPane().add(_tf_user_loging_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 300, -1));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 300, 10));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/img_logo200x200.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 310, 250));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 300, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Forget Password?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 510, 290, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/img_ShowPassword.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 330, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/middlle_235997.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 360, 330));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Managment System");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 290, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Test Version");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 510, 120, -1));

        seperatorBar.setBackground(new java.awt.Color(255, 255, 255));
        seperatorBar.setForeground(new java.awt.Color(255, 255, 255));
        seperatorBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/img_SaperateBar.png"))); // NOI18N
        getContentPane().add(seperatorBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 10, 350));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/back.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new Thread(() -> {
                jProgressBar1.setIndeterminate(true);
            }).start();
            new Thread(() -> {

                login_user_method();

            }).start();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void _pf_user_login_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__pf_user_login_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__pf_user_login_passwordActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        _pf_user_login_password.setEchoChar((char) 0);

    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased

        _pf_user_login_password.setEchoChar('#');

    }//GEN-LAST:event_jLabel1MouseReleased

    private void lb_exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseReleased

        System.exit(0);

    }//GEN-LAST:event_lb_exitMouseReleased

    private void _tf_user_loging_userNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_user_loging_userNameKeyTyped

        _tf_user_loging_userName.setBackground(Color.WHITE);

    }//GEN-LAST:event__tf_user_loging_userNameKeyTyped

    private void _pf_user_login_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__pf_user_login_passwordKeyTyped

        _pf_user_login_password.setBackground(Color.WHITE);

    }//GEN-LAST:event__pf_user_login_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new user_login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField _pf_user_login_password;
    private javax.swing.JTextField _tf_user_loging_userName;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lb_date_view;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_time_date;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel seperatorBar;
    // End of variables declaration//GEN-END:variables

    public void login_user_method() {

        String pass = new String(_pf_user_login_password.getPassword());
        try {

            ResultSet rs;
            rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery("SELECT * FROM user WHERE user_email='" + _tf_user_loging_userName.getText() + "' AND user_password='" + pass + "'");
            if (rs.next()) {
                String s = rs.getString("user_status");
                int i = Integer.parseInt(s);

                if (i == 1) {
                    System.out.println("User Logged!");
                    User_home user_menu = new User_home();
                    user_menu.setVisible(true);
                    user_menu.load_username(_tf_user_loging_userName.getText().trim());

                    this.dispose();
                } else {

                    jProgressBar1.setIndeterminate(false);

                    JOptionPane.showMessageDialog(this, "Your are not Active user");
                    _pf_user_login_password.setBackground(Color.RED);
                    _tf_user_loging_userName.setBackground(Color.RED);
                }

                System.gc();

            } else {

                jProgressBar1.setIndeterminate(false);

                JOptionPane.showMessageDialog(this, "Please chack your email or Password!");
                _tf_user_loging_userName.grabFocus();
            }

            rs.close();
        } catch (SQLException | NumberFormatException | HeadlessException e) {
            e.printStackTrace();
        }

    }

    void showTime() {
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat stim = new SimpleDateFormat("hh:mm:ss a");
            String st = stim.format(d);
            lb_time_date.setText(st);
        }).start();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String s = sdf.format(d);
        lb_date_view.setText(s);
        System.out.println(s);

    }
}
