/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.ayolan.public_access.user.login;

import java.awt.Color;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author deepalsuranga
 */
public class User_home extends javax.swing.JFrame {

    /**
     * Creates new form User_home
     */
    public User_home() {
        initComponents();
        this.getContentPane().setBackground(new Color(61, 61, 61));

        jScrollPane1.setVisible(false);

    }

    public void my(String string) {
        lb_username.setText(string);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        li_menu = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_username.setForeground(new java.awt.Color(255, 255, 255));
        lb_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_username.setText("WelCome");
        lb_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_usernameMouseClicked(evt);
            }
        });
        jPanel1.add(lb_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1097, 11, 259, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        li_menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        li_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "User Settings", "My Account", "Go drashboard", "Logout" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        li_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                li_menuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(li_menu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 50, 180, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int i = 1;
    private void lb_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_usernameMouseClicked

        if (i > 0) {
            jScrollPane1.setVisible(true);

            i--;
        } else {

            jScrollPane1.setVisible(false);
            i++;
        }


    }//GEN-LAST:event_lb_usernameMouseClicked

    private void li_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_li_menuMouseClicked

        li_menu.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                System.out.println("index :" + li_menu.getSelectedIndex());
            }
        });

//        this.dispose();
//        new user_login().setVisible(true);

    }//GEN-LAST:event_li_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User_home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lb_username;
    private javax.swing.JList<String> li_menu;
    // End of variables declaration//GEN-END:variables
}
